import './globals.css';

import type { Metadata } from 'next';

import BackgroundPattern from '@/components/BackgroundPattern';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="font-sans antialiased text-neutral-800">
        <BackgroundPattern />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
